apiVersion: v1
kind: Service
metadata:
  name: greeting-svc
  namespace: cloud-native-test
spec:
  type: NodePort
  selector:
    app: greeting
  ports:
  - nodePort: 30888
    port: 8080
    targetPort: 8080